micronaut:
  application:
    name: exchange-service
  server:
    port: 8989
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    client:
      read-timeout: 5s
      connect-timeout: 5s

logger:
  levels:
    dev.insidemind.exchange: INFO
    io.micronaut.context.condition: INFO

jackson:
  serialization:
    writeDatesAsTimestamps: false

bank:
  api:
    nbp:
      url: http://api.nbp.pl/api
