micronaut:
  application:
    name: bank
  server:
    port: 8989
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

logger:
  levels:
    dev.insidemind.bank: DEBUG
    io.micronaut.context.condition: INFO

jackson:
  serialization:
    writeDatesAsTimestamps: false
