POST http://localhost:8989/account/
Content-Type: application/json

{
  "name": "String",
  "surname": "String",
  "pesel": "84080808057",
  "amount": "1000"
}

###
GET http://localhost:8989/account/84080808057


####
PUT http://localhost:8989/account/exchange/usd
Content-Type: application/json

{
  "accountId": "84080808057",
  "amount": "5"
}

####
PUT http://localhost:8989/account/exchange/pln
Content-Type: application/json

{
  "accountId": "84080808057",
  "amount": "5"
}
