POST http://localhost:8989/account/
Content-Type: application/json

{
  "name": "String",
  "surname": "String",
  "pesel": "String",
  "amount": "1234.213"
}

###
GET http://localhost:8989/account/31232132
