POST http://localhost:8989/account/
Content-Type: application/json

{
  "name": "String",
  "surname": "String",
  "pesel": "08484848451",
  "amount": "1234,215565"
}

###
GET http://localhost:8989/account/31232132
